name: super-linter 

on: push

jobs:
  superlint:
     name: linmt code base
     runs-on: ubuntu-latest
     
     steps:
       - name: checkout code
         uses: actions/checkout@v2
         
       - name: Super-Linter
  # You may pin to the exact commit or the version.
  # uses: super-linter/super-linter@45fc0d88288beee4701c62761281edfee85655d7
         uses: super-linter/super-linter@v5.0.0
         env:
           DEFAULT_BRANCH: MAIN
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
  
